In [1]:
import torch

In [2]:
x = torch.empty(2,3)

In [3]:
x

tensor([[6.3639e-02, 8.2536e-43, 6.3639e-02],
        [8.2536e-43, 6.3621e-02, 8.2536e-43]])

In [4]:
x = torch.rand(2,2)

In [5]:
x

tensor([[0.7996, 0.4875],
        [0.5295, 0.4172]])

In [6]:
x = torch.ones(2,2)

In [7]:
x

tensor([[1., 1.],
        [1., 1.]])

In [8]:
x = torch.tensor([2.5, 0.1])

In [9]:
x = torch.rand(2,2)
print(x)

tensor([[0.8926, 0.3242],
        [0.6826, 0.0936]])


In [10]:
y = torch.rand(2,2)
print(y)

tensor([[0.4458, 0.6503],
        [0.0116, 0.4342]])


- Elementwise addition

In [11]:
z = x + y
print(z)

tensor([[1.3384, 0.9745],
        [0.6942, 0.5278]])


In [12]:
c = torch.add(x,y)
print(c)

tensor([[1.3384, 0.9745],
        [0.6942, 0.5278]])


In [13]:
y.add_(x)
# updates values of y inplace

tensor([[1.3384, 0.9745],
        [0.6942, 0.5278]])

In [14]:
x = torch.rand(5,3)
print(x[:,0])

tensor([0.0385, 0.5802, 0.1722, 0.9887, 0.7956])


In [15]:
print(x[0,0].item())
# removes the tensor which is printed and returns the whole value of the number

0.03851240873336792


In [16]:
x = torch.rand(4,4)

In [17]:
x.view(16)

tensor([0.4951, 0.6450, 0.2935, 0.8117, 0.4399, 0.1293, 0.2402, 0.5863, 0.1524,
        0.8709, 0.9689, 0.7479, 0.8389, 0.5353, 0.7990, 0.5639])

In [18]:
x.view(-1,8)

tensor([[0.4951, 0.6450, 0.2935, 0.8117, 0.4399, 0.1293, 0.2402, 0.5863],
        [0.1524, 0.8709, 0.9689, 0.7479, 0.8389, 0.5353, 0.7990, 0.5639]])

In [19]:
x.view(8,-1)

tensor([[0.4951, 0.6450],
        [0.2935, 0.8117],
        [0.4399, 0.1293],
        [0.2402, 0.5863],
        [0.1524, 0.8709],
        [0.9689, 0.7479],
        [0.8389, 0.5353],
        [0.7990, 0.5639]])

- converting numpy array to tensor

In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

In [21]:
a

array([1., 1., 1., 1., 1.])

In [22]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [23]:
a += 1
a

array([2., 2., 2., 2., 2.])

In [24]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [25]:
b = b.add(1)
b

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)

In [26]:
a

array([2., 2., 2., 2., 2.])

when converting numpy to tensor, if the numpy array is updated the tensor is updated too but when the tensor is updated the numpy array does not update itself

- converting tensor to numpy array

In [27]:
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [28]:
a -= 1
a

tensor([0., 0., 0., 0., 0.])

In [29]:
b

array([0., 0., 0., 0., 0.], dtype=float32)

In [30]:
b -= 1
b

array([-1., -1., -1., -1., -1.], dtype=float32)

In [31]:
a

tensor([-1., -1., -1., -1., -1.])

- when converting tensor to a numpy array, if the tensor is updated the numpy array is updated too. Vice versa is also true

### Gradient calculation

In [32]:
x = torch.rand(3, requires_grad=True)
y = x + 2

In [33]:
print(x)
print(y)

tensor([0.7666, 0.4151, 0.1575], requires_grad=True)
tensor([2.7666, 2.4151, 2.1575], grad_fn=<AddBackward0>)


In [34]:
z = y * y * 2
print(z)

tensor([15.3083, 11.6655,  9.3096], grad_fn=<MulBackward0>)


In [35]:
out = z.mean()
print(z)

tensor([15.3083, 11.6655,  9.3096], grad_fn=<MulBackward0>)


In [36]:
out.backward()
print(x.grad)

tensor([3.6888, 3.2201, 2.8767])


In [37]:
# f = w * x
# f = 2 * x

X = np.array([1,2,3,4], dtype=np.float32) # input values
Y = np.array([2,4,6,8], dtype=np.float32) # target values
w = 0.0 # initialise weight

In [38]:
# model prediction
def forward(x):
  return w * x
# y_hat = w * x

In [39]:
# loss = MSE
# MSE = 1/N * (y_hat - y)**2
def loss(y, y_hat):
  return ((y_hat - y) ** 2).mean()

In [40]:
 
# gradient
# dJ/dw = 1/N *2X(y_hat - y)
def gradient(x, y, y_hat):
    return np.dot(2*X, y_hat - y).mean()


In [41]:
print(f"Prediction before training: f(5) = {forward(5)}")

Prediction before training: f(5) = 0.0


In [46]:
learning_rate = 0.01
n_iters = 30
for epoch in range(n_iters):
    #prediction -> forward pass
    y_hat = forward(X)
    
    #loss
    l = loss(Y, y_hat)
    
    # gradient descent
    dw = gradient(X, Y, y_hat)
    
    # update weights
    w -= learning_rate * dw
    
    if epoch % 2 == 0:
        print(f"epoch {epoch+1}: w = {w:.2f}, loss = {l:.2f}")

epoch 1: w = 2.00, loss = 0.00
epoch 3: w = 2.00, loss = 0.00
epoch 5: w = 2.00, loss = 0.00
epoch 7: w = 2.00, loss = 0.00
epoch 9: w = 2.00, loss = 0.00
epoch 11: w = 2.00, loss = 0.00
epoch 13: w = 2.00, loss = 0.00
epoch 15: w = 2.00, loss = 0.00
epoch 17: w = 2.00, loss = 0.00
epoch 19: w = 2.00, loss = 0.00
epoch 21: w = 2.00, loss = 0.00
epoch 23: w = 2.00, loss = 0.00
epoch 25: w = 2.00, loss = 0.00
epoch 27: w = 2.00, loss = 0.00
epoch 29: w = 2.00, loss = 0.00


In [47]:
print(f"Prediction after training: f(5) = {forward(5):.4f}")

Prediction after training: f(5) = 10.0000
